# Generated by Django 5.2.7 on 2025-12-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_buyflight_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
